### ISSUE TITLE
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 8.x

### ISSUE THREAD

**Issue by GabLeRoux** [GabLeRoux/rails-webpacker-scss-example#1]
```
Using /app/config/webpacker.yml file for setting up webpack paths
Compiling…
Compilation failed:
Hash: 3c10898301458687a37b
Version: webpack 3.11.0
Time: 5029ms
                                              Asset       Size  Chunks             Chunk Names
                application-daccb0a9b28c039cbcf1.js    8.71 kB    0, 1  [emitted]  application
    stylesheets/application-1792e16c717acfa897ea.js    7.85 kB       1  [emitted]  stylesheets/application
            application-daccb0a9b28c039cbcf1.js.map    3.25 kB    0, 1  [emitted]  application
stylesheets/application-1792e16c717acfa897ea.js.map     2.5 kB       1  [emitted]  stylesheets/application
                                      manifest.json  330 bytes          [emitted]
   [0] ./app/javascript/packs/stylesheets/application.scss 5.06 kB {0} {1} [built] [failed] [1 error]
   [1] ./app/javascript/packs/application.js 559 bytes {0} [built]
   [2] ./node_modules/css-loader??ref--2-2!./node_modules/postcss-loader/lib??ref--2-3!./node_modules/sass-loader/lib/loader.js??ref--2-4!./app/javascript/packs/stylesheets/application.scss 2.4 kB [built] [failed] [1 error]
    + 2 hidden modules

ERROR in ./node_modules/css-loader??ref--2-2!./node_modules/postcss-loader/lib??ref--2-3!./node_modules/sass-loader/lib/loader.js??ref--2-4!./app/javascript/packs/stylesheets/application.scss
Module build failed: Error: Missing binding /app/node_modules/node-sass/vendor/linux-x64-57/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 8.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 8.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (/app/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/app/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at loadLoader (/app/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /app/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/app/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /app/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/app/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/app/node_modules/webpack/lib/NormalModule.js:182:3)
    at NormalModule.build (/app/node_modules/webpack/lib/NormalModule.js:275:15)
 @ ./app/javascript/packs/stylesheets/application.scss 2:14-224

ERROR in ./app/javascript/packs/stylesheets/application.scss
Module build failed: ModuleBuildError: Module build failed: Error: Missing binding /app/node_modules/node-sass/vendor/linux-x64-57/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 8.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 8.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (/app/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/app/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at loadLoader (/app/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /app/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/app/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /app/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/app/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/app/node_modules/webpack/lib/NormalModule.js:182:3)
    at NormalModule.build (/app/node_modules/webpack/lib/NormalModule.js:275:15)
    at runLoaders (/app/node_modules/webpack/lib/NormalModule.js:195:19)
    at /app/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /app/node_modules/loader-runner/lib/LoaderRunner.js:170:18
    at loadLoader (/app/node_modules/loader-runner/lib/loadLoader.js:27:11)
    at iteratePitchingLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /app/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/app/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /app/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/app/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/app/node_modules/webpack/lib/NormalModule.js:182:3)
    at NormalModule.build (/app/node_modules/webpack/lib/NormalModule.js:275:15)
    at Compilation.buildModule (/app/node_modules/webpack/lib/Compilation.js:151:10)
    at moduleFactory.create (/app/node_modules/webpack/lib/Compilation.js:454:10)
    at factory (/app/node_modules/webpack/lib/NormalModuleFactory.js:243:5)
    at applyPluginsAsyncWaterfall (/app/node_modules/webpack/lib/NormalModuleFactory.js:94:13)
    at /app/node_modules/tapable/lib/Tapable.js:268:11
    at NormalModuleFactory.params.normalModuleFactory.plugin (/app/node_modules/webpack/lib/CompatibilityPlugin.js:52:5)
    at /app/node_modules/tapable/lib/Tapable.js:270:14
    at that.fileExistsWithCase (/app/node_modules/case-sensitive-paths-webpack-plugin/index.js:159:13)
    at that.fileExistsWithCase (/app/node_modules/case-sensitive-paths-webpack-plugin/index.js:109:7)
    at CaseSensitivePathsPlugin.fileExistsWithCase (/app/node_modules/case-sensitive-paths-webpack-plugin/index.js:79:5)
    at that.getFilenamesInDir (/app/node_modules/case-sensitive-paths-webpack-plugin/index.js:102:10)
    at CaseSensitivePathsPlugin.getFilenamesInDir (/app/node_modules/case-sensitive-paths-webpack-plugin/index.js:47:5)
    at CaseSensitivePathsPlugin.fileExistsWithCase (/app/node_modules/case-sensitive-paths-webpack-plugin/index.js:85:8)
    at that.primeCache (/app/node_modules/case-sensitive-paths-webpack-plugin/index.js:150:14)
 @ ./app/javascript/packs/stylesheets/application.scss
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--2-2!node_modules/postcss-loader/lib/index.js??ref--2-3!node_modules/sass-loader/lib/loader.js??ref--2-4!app/javascript/packs/stylesheets/application.scss:
       [0] ./node_modules/css-loader??ref--2-2!./node_modules/postcss-loader/lib??ref--2-3!./node_modules/sass-loader/lib/loader.js??ref--2-4!./app/javascript/packs/stylesheets/application.scss 2.4 kB {0} [built] [failed] [1 error]

    ERROR in ./node_modules/css-loader??ref--2-2!./node_modules/postcss-loader/lib??ref--2-3!./node_modules/sass-loader/lib/loader.js??ref--2-4!./app/javascript/packs/stylesheets/application.scss
    Module build failed: Error: Missing binding /app/node_modules/node-sass/vendor/linux-x64-57/binding.node
    Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 8.x

    Found bindings for the following environments:
      - OS X 64-bit with Node.js 8.x

    This usually happens because your environment has changed since running `npm install`.
    Run `npm rebuild node-sass --force` to build the binding for your current environment.
        at module.exports (/app/node_modules/node-sass/lib/binding.js:15:13)
        at Object.<anonymous> (/app/node_modules/node-sass/lib/index.js:14:35)
        at Module._compile (module.js:643:30)
        at Object.Module._extensions..js (module.js:654:10)
        at Module.load (module.js:556:32)
        at tryModuleLoad (module.js:499:12)
        at Function.Module._load (module.js:491:3)
        at Module.require (module.js:587:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/app/node_modules/sass-loader/lib/loader.js:3:14)
        at Module._compile (module.js:643:30)
        at Object.Module._extensions..js (module.js:654:10)
        at Module.load (module.js:556:32)
        at tryModuleLoad (module.js:499:12)
        at Function.Module._load (module.js:491:3)
        at Module.require (module.js:587:17)
        at require (internal/module.js:11:18)
        at loadLoader (/app/node_modules/loader-runner/lib/loadLoader.js:13:17)
        at iteratePitchingLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at iteratePitchingLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
        at /app/node_modules/loader-runner/lib/LoaderRunner.js:173:18
        at loadLoader (/app/node_modules/loader-runner/lib/loadLoader.js:36:3)
        at iteratePitchingLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at iteratePitchingLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
        at /app/node_modules/loader-runner/lib/LoaderRunner.js:173:18
        at loadLoader (/app/node_modules/loader-runner/lib/loadLoader.js:36:3)
        at iteratePitchingLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at runLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
        at NormalModule.doBuild (/app/node_modules/webpack/lib/NormalModule.js:182:3)
        at NormalModule.build (/app/node_modules/webpack/lib/NormalModule.js:275:15)


/usr/local/bundle/gems/webpacker-3.2.2/lib/webpacker/dev_server_runner.rb:47:in `exec': No such file or directory - /app/node_modules/.bin/webpack-dev-server (Errno::ENOENT)
	from /usr/local/bundle/gems/webpacker-3.2.2/lib/webpacker/dev_server_runner.rb:47:in `block in execute_cmd'
	from /usr/local/bundle/gems/webpacker-3.2.2/lib/webpacker/dev_server_runner.rb:46:in `chdir'
	from /usr/local/bundle/gems/webpacker-3.2.2/lib/webpacker/dev_server_runner.rb:46:in `execute_cmd'
	from /usr/local/bundle/gems/webpacker-3.2.2/lib/webpacker/dev_server_runner.rb:11:in `run'
	from /usr/local/bundle/gems/webpacker-3.2.2/lib/webpacker/runner.rb:6:in `run'
	from /usr/local/bundle/gems/webpacker-3.2.2/exe/webpack-dev-server:8:in `<top (required)>'
	from /usr/local/bundle/bin/webpack-dev-server:29:in `load'
	from /usr/local/bundle/bin/webpack-dev-server:29:in `<main>'
```

**Comment by GabLeRoux** [comment]
```bash
docker-compose exec web npm rebuild node-sass --force
```

Fixed the problem
